number1=int (input("anna kokonaisluku"))
number2=int (input ("anna toinen kokonaisluku"))
print ("summa") 
print(number1+number2)
print("erotus")
print(number1-number2)
print("tulo")
print(number1*number2)
